### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by martinshkreli** [martinshkreli/shchem#33]

**Comment by jsdir** [comment]
logs:
```
2017-03-24T20:01:05.909978+00:00 app[web.1]: GET /bundle.js 200 2.258 ms - 1578441
2017-03-24T20:01:05.938828+00:00 heroku[router]: at=info method=GET path="/bundle.js" host=shchem.herokuapp.com request_id=1514479d-f0a2-4b4b-b9f0-3b848f11c6e1 fwd="50.162.89.57" dyno=web.1 connect=0ms service=54ms status=200 bytes=1578734 protocol=https
2017-03-24T20:01:09.486269+00:00 app[web.1]: Unhandled rejection TypeError: Object.entries is not a function
2017-03-24T20:01:09.486279+00:00 app[web.1]:     at compoundToJson (/app/server/controllers/api/v1/compounds.js:16:10)
2017-03-24T20:01:09.486281+00:00 app[web.1]:     at res.json.compounds.map (/app/server/controllers/api/v1/compounds.js:41:35)
2017-03-24T20:01:09.486281+00:00 app[web.1]:     at Array.map (native)
2017-03-24T20:01:09.486282+00:00 app[web.1]:     at Model.CompoundView.findAll.then (/app/server/controllers/api/v1/compounds.js:41:17)
2017-03-24T20:01:09.486283+00:00 app[web.1]:     at Model.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2017-03-24T20:01:09.486284+00:00 app[web.1]:     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
2017-03-24T20:01:09.486285+00:00 app[web.1]:     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
2017-03-24T20:01:09.486285+00:00 app[web.1]:     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
2017-03-24T20:01:09.486286+00:00 app[web.1]:     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:693:18)
2017-03-24T20:01:09.486287+00:00 app[web.1]:     at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
2017-03-24T20:01:09.486287+00:00 app[web.1]:     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
2017-03-24T20:01:09.486288+00:00 app[web.1]:     at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
2017-03-24T20:01:09.486289+00:00 app[web.1]:     at runCallback (timers.js:666:20)
2017-03-24T20:01:09.486290+00:00 app[web.1]:     at tryOnImmediate (timers.js:639:5)
2017-03-24T20:01:09.486291+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:611:5)
```
